networks:
  app-tier:
    driver: bridge

services:
  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - app-tier
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  kafka-init:
    image: 'bitnami/kafka:latest'
    depends_on:
      - kafka
    networks:
      - app-tier
    entrypoint: ["./kafka-populate.sh"]
    env_file:
       - ./env.kafka-populate
    volumes:
       - ./kafka-populate.txt:/kafka-populate.txt
       - ./kafka-populate.sh:/kafka-populate.sh
  myapp:
    image: 'supplyplanning:latest'
    depends_on:
      - kafka-init
    networks:
      - app-tier
    
